name: 'Artifact'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            css/
            ico/
            LICENSE
            NOTICE
